#define HELLO_MESSAGE "Здравствуйте!Я Mr Steel Rat  и пришлю Вам необходимую информацию."
#define URL_VK "https://vk.com/mrsteelrat"
#define URL_TG "https://t.me/MrSteelRat"
#define UTL_GITHUB "https://github.com/MrSteelRat"
#define URL_YOUTUBE "https://www.youtube.com/@MrSteelRat-bm2uv"
#define URL_BOOSTY "https://boosty.to/mrsteelrat"
#define URL_DONAT_ALERT "https://www.donationalerts.com/r/mrsteelrat"
#define URL_WEBSITE "https://mrsteelrat.site/"
